version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:sqlserver://localhost:1433;databaseName=ppfbank
#      SPRING_DATASOURCE_USERNAME: admin1
#      SPRING_DATASOURCE_PASSWORD: Pass1234
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: true
#    depends_on:
#      - db

  db:
    image: postgres:latest
    container_name: ppfbank
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ppfbank-db
    networks:
      - internal
#  db:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    environment:
#      SA_PASSWORD: MyStrongPass123
#      ACCEPT_EULA: "Y"
#      MSSQL_PID: "Express"
#    ports:
#      - "1433:1433"
#    volumes:
#      - ./src/main/resources/db/entrypoint.sh:/entrypoint.sh
#      - ./src/main/resources/db/ta_database_init.sql:/src/main/resources/db/ta_database_init.sql
#      - ./src/main/resources/db/ta_database.sql:/src/main/resources/db/ta_database.sql
#      - ./src/main/resources/db/ta_populate.sql:/src/main/resources/db/ta_populate.sql
#    entrypoint: ["bash", "/entrypoint.sh"]
