version: '3.8'

services:
  db:
    build: .
    environment:
      SA_PASSWORD: MyStrongPass123
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./src/main/resources/db:/src/main/resources/db
    entrypoint: ["bash", "/entrypoint.sh"]