version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://localhost:1433;databaseName=ppfbank
      SPRING_DATASOURCE_USERNAME: admin1
      SPRING_DATASOURCE_PASSWORD: Pass1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    command: /bin/bash ./entrypoint.sh
    environment:
      SA_PASSWORD: MyStrongPass123
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data
      - CreateDatabase/docker-entrypoint.sh:/entrypoint.sh
      - CreateDatabase/docker-db-init.sh:/db-init.sh
      - CreateDatabase/ankara-db-init.sql:/ankara-db-init.sql
