version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: ppfbank-api
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=ppfbank-db;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: admin1
      SPRING_DATASOURCE_PASSWORD: Pass1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.SQLServerDialect
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    depends_on:
      - db

  db:
    build: .
    environment:
      SA_PASSWORD: MyStrongPass123
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - .:/app
      - ./src/main/resources/db:/src/main/resources/db
    entrypoint: ["bash", "/app/entrypoint.sh"]