CREATE DATABASE [ppfbank-db]
GO

USE [ppfbank-db];
GO

CREATE LOGIN [admin1] WITH PASSWORD = 'Pass1234'
GO

CREATE SCHEMA app
GO

CREATE USER [admin1] FOR LOGIN [admin1] WITH DEFAULT_SCHEMA=[app]
GO

ALTER ROLE db_owner ADD MEMBER [admin1]
GO